### ISSUE TITLE
End point lanes change, unexpectedly, when start point lanes are changed

### ISSUE THREAD

**Issue by bdog2112** [TheDuckCow/godot-road-generator#80] opened 2023-03-23 16:49 UTC
Observed an intermittent issue that we've seen many times in the past. However, I thought it was attributed to the IDE being unstable after plugin edits, which is to be expected But, now I think it's something else and I found some steps that help to re-create it for further troubleshooting.

ISSUE: Sometimes the "end point" number of lanes changes when the user changes number of lanes on the "start point".

In the image below, one lane was added to the top RoadPoint and the middle RoadPoint unexpectedly also added a lane. The expected behavior is for lanes to be added only to the selected RoadPoint.

![lanes_issue_1](https://user-images.githubusercontent.com/115952055/227272526-7ff1b850-bff3-4e44-aa13-99f4007a4d1f.png)

Steps to re-create the problem:
- Create a new scene
- Create a 2x2 road
- Select the last RoadPoint and click "+ Next RoadPoint" to add a 3rd point
- Save, close, and re-open the scene
- Select the first RoadPoint and add a lane
- The second RoadPoint should unexpectedly, also, add a lane

Not all RoadPoints exhibit the problem. But, if you limit the test case to the simple road network described, above, you should be able to observe the issue.

**Comment by TheDuckCow** [comment] 2023-06-18 00:31
As far as I understand now, @bdog2112 we actually already resolved this bug right?

Closing the issue as I can't reproduce this now (and I recall we came to a solution to linked arrays), but please comment if you recall otherwise and think this is still open.

**Closed by TheDuckCow** 2023-06-18 00:31 UTC
Labels: bug

**Comment by bdog2112** [comment] 2023-06-18 03:23
Yes. This was fixed when array initialization was moved to the _init routine.
